# docker-compose.load-test.yml
version: '3.8'

services:
  locust:
    image: locustio/locust:2.20.0
    container_name: kedo_locust
    ports:
      - "8089:8089"
    volumes:
      - ./backend/tests/locustfile.py:/locust/locustfile.py
      - ./reports:/locust/reports
    environment:
      - LOCUST_HOST=http://backend:8000
    command: >
      --host=http://backend:8000
    networks:
      - kedo_network

networks:
  kedo_network:
    external: true
    name: kedo_default 